#!/bin/bash

# Copyright (c) 2018, Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#https://github.com/longsleep/build-pine64-image/blob/master/simpleimage/platform-scripts/pine64_health.sh
#---------------Configuration-------------#
#source common.sh nofunc
NORM="$(tput sgr0)"
BOLD="$(tput bold)"
REV="$(tput smso)"
UND="$(tput smul)"
BLACK="$(tput setaf 0)"
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
BLUE="$(tput setaf 4)"
MAGENTA="$(tput setaf 5)"
CYAN="$(tput setaf 6)"
WHITE="$(tput setaf 7)"
ERROR="${REV}Error:${NORM}"
version="1.5"
LogToTerm=1
loglevel=info;
regenerateStats=0;



#/	Desc:	Gathers all the keys from the menu system and builds a proper string for getopts	
#/	Out:	echo - switch_conditions
#/	Expl:	switch_conditions=$(COMMON_MENU_SWITCH_GRAB)
COMMON_MENU_SWITCH_GRAB(){
	#shellcheck disable=SC2154
	for KEY in "${!hp[@]}"; do
		:
		VALUE=${hp[$KEY]}
		numcheck="${KEY:1:1}"
		skip=false
		if [[ "$numcheck" =~ ^[0-9]+$ ]]; then
			skip=true
		fi
		double=""
		if [[ ${#KEY} -gt 1 ]]; then
			double=":"
			dKEY="${KEY:0:1}"
		else
			dKEY=$KEY
		fi
		if [[ $KEY != "description" && $KEY != "useage" && $skip != true ]]; then
			myline=$myline$dKEY$double
		fi
	done
	echo "$myline"
} #end_COMMON_MENU_SWITCH_GRAB

#/	Desc:	Generates a menu based on a named template system
#/  Global: declare -A hp=() assoiative array of switches
#/			exects an associateve array named hp.
#/			hp nomenclature hp[x] where x represents a switch
#/			and where hp[xx] represents a switch and varriable
#/	$1:		[error text]  OPTIONAL
#/	$2:		name1
#/	$3:		name1
#/	Out:	a help text for the cli
#/	Expl:	COMMON_MENU_HELP
COMMON_MENU_HELP(){
	if [[ $1 != "" ]]; then
		echo -e "\nERROR: ${REV}${BOLD}$1${NORM}"
	fi
	echo -e \\n"Help documentation for ${BOLD}$0${NORM}"
	echo -e "${hp[description]}"
	echo -e "----------------------------------------------------------------------------------------"
	echo -e "${BOLD}Basic usage:${NORM}${BOLD} $0 ${NORM} ${hp[useage]}"
	etext=""
	for KEY in "${!hp[@]}"; do
		:
		VALUE=${hp[$KEY]}
		numcheck="${KEY:1:1}"
		skip=false
		if [[ "$numcheck" =~ ^[0-9]+$ ]]; then
			skip=true
			if [[ ${KEY:0:1} = "e" ]]; then
				etext=$etext"${UND}${BOLD} Example:${NORM} $VALUE\n"
			fi
		fi
		if [[ ${#KEY} -gt 1 ]]; then
			dKEY="${KEY:0:1}"
		else
			dKEY=$KEY
		fi
		if [[ $KEY != "description" && $KEY != "useage" && $skip != true ]]; then
			switches=$switches"${BOLD}-$dKEY${NORM} $VALUE\n"
		fi
	done  
	echo -e "$switches"  | sort -n -k1
	echo -e "$etext\n"
	exit 1
} #end_COMMON_MENU_HELP


idmachine(){
	source /etc/os-release
	if [[ $LMP_MACHINE = "imx8mmevk" || $LMP_MACHINE = "uz3eg-iocc" ]]; then
		PTYPE="2"
		hardwareVersion="$LMP_MACHINE"
		IPADDRESS=$(ifconfig | grep inet | grep -v '127.0.0.1' | grep -v 'inet6' | cut -d: -f2 | awk '{print $2}')
	else
		PTYPE="1"
		IPADDRESS=$(ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}')
	fi

}

_check_stat_var_set_error=0;
_check_stat_var_set(){
	#echo -en "checking $1: "
	if [[ $1 = "" ]]; then
		_check_stat_var_set_error=1
	fi
	#echo "$_check_stat_var_set_error"
}

load_statistics(){
	if [[ $regenerateStats -eq 1 ]]; then
		rm -rf /wigwag/system/lib/bash/relaystatics.sh

	fi
	if [[ -e "/wigwag/system/lib/bash/relaystatics.sh" ]]; then
		source "/wigwag/system/lib/bash/relaystatics.sh"
		_check_stat_var_set "$serialNumber"
		_check_stat_var_set "$OU"
		_check_stat_var_set "$deviceID"
		_check_stat_var_set "$hardwareVersion"
		_check_stat_var_set "$radioConfig"
		_check_stat_var_set "$ledConfig"
		_check_stat_var_set "$category"
		_check_stat_var_set "$ethernetMAC_0"
		_check_stat_var_set "$ethernetMAC_1"
		_check_stat_var_set "$ethernetMAC_2"
		_check_stat_var_set "$ethernetMAC_3"
		_check_stat_var_set "$ethernetMAC_4"
		_check_stat_var_set "$ethernetMAC_5"
		_check_stat_var_set "$sixBMAC_0"
		_check_stat_var_set "$sixBMAC_1"
		_check_stat_var_set "$sixBMAC_2"
		_check_stat_var_set "$sixBMAC_3"
		_check_stat_var_set "$sixBMAC_4"
		_check_stat_var_set "$sixBMAC_5"
		_check_stat_var_set "$sixBMAC_6"
		_check_stat_var_set "$sixBMAC_7"
		_check_stat_var_set "$gatewayServicesAddress"
		_check_stat_var_set "$edgek8sServicesAddress"
		_check_stat_var_set "$cloudAddress"
		if [[ $_check_stat_var_set_error -ne 0 ]]; then
			echo "Stats out of sync, relaoding..."
			rm -rf /wigwag/system/lib/bash/relaystatics.sh
			if [[ -e /userdata/edge_gw_config/identity.json ]]; then
				/wigwag/system/bin/json2sh /userdata/edge_gw_config/identity.json /wigwag/system/lib/bash/relaystatics.sh
				source "/wigwag/system/lib/bash/relaystatics.sh"
			fi
		fi
	else
		if [[ -e /userdata/edge_gw_config/identity.json ]]; then
			/wigwag/system/bin/json2sh /userdata/edge_gw_config/identity.json /wigwag/system/lib/bash/relaystatics.sh
			source "/wigwag/system/lib/bash/relaystatics.sh"
		fi
	fi
}

#run eetool


_placeTitle(){
	TITLE="$1"
	echo -e "\n${YELLOW}$TITLE${NORM}"
}

_exec(){
	local cmd="$1"
	out=$(eval "$cmd" >> /dev/null 2>&1)
	if [[ $? -eq 0 ]]; then
		echo "$out"
	fi
}
_placeLine(){
	SUBJECT="$1"
	BODY="${2:-n/a}"
	len="${#SUBJECT}"
	#echo "$len"
	echo -en "$SUBJECT"
	if [[ $len -lt 8 ]]; then
		echo -en "\t\t\t\t"
	elif [[ $len -lt 16 ]]; then
		echo -en "\t\t\t"
	elif [[ $len -lt 24 ]]; then
		echo -en "\t\t"
	elif [[ $len -lt 32 ]]; then
		echo -en "\t"
	else
		echo -en "";
	fi
	echo -e "${CYAN}$BODY${NORM}"
}

_placeHeader(){
	echo -e "\n\n${RED}$1 ${NORM}"
}

_div1000(){
	out=$(bc <<< "scale=1; $1 / 1000")
	if [[ "$out" = *".0" ]]; then
		out=$(bc <<< "scale=0; $1 / 1000")
	fi
	echo "$out"
}
_div1000b(){
	out=$(bc <<< "scale=0; $1 / 1000")
	if [[ "$out" = *".0" ]]; then
		out=$(bc <<< "scale=0; $1 / 1000")
	fi
	echo "$out"
}
_div1024(){
	out=$(bc <<< "scale=1; $1 / 1024")
	echo "$out"
}

_percentage(){
	if [[ $1 = 0 || $1 = "" || $2 = 0 || $2 = "" ]]; then
		echo "0"
	else
		echo $(bc <<< "scale=2; $1*100/$2")
	fi
}

function jsonParse()
{
	echo $1 | \
	sed -e 's/[{}]/''/g' | \
	sed -e 's/", "/'\",\"'/g' | \
	sed -e 's/","/'\"---BREAK---\"'/g' | \
	awk -F=':' -v RS='---BREAK---' "\$1~/\"$2\"/ {print}" | \
	sed -e "s/\"$2\"://" | \
	tr -d "\n\t" | \
	sed -e 's/^"//'  -e 's/"$//'
}

MEM=$(grep MemTotal /proc/meminfo | awk '{print $2}')
MEM=$(_div1000b "$MEM")
AVAILABLE=$(free -m | awk 'NR==2{printf $7}')
#USED=$(free -m | awk 'NR==2{printf $3}')
USED=$(bc <<< "scale=1; $MEM - $AVAILABLE");
#remainder=$(bc <<< "scale=1; $volatilePSS + $PSSTOT + $r2")
UMP=$(_percentage $USED $MEM)
#UMP=$(bc <<< "scale=2; $USED*100/$MEM")
volatilePSS=$(df -h | grep volatile | awk '{print $3}');
if [[ $volatilePSS = *"K" ]]; then
	volatilePSS=1
else
	volatilePSS=${volatilePSS::-1}
	if [[ $volatilePSS = "" ]]; then
		volatilePSS=0
	fi
fi
USEDMMC=$(mount | grep factory | head -1 | awk -F "/" '{print $3}' | awk -F " " '{print $1}');USEDMMC=${USEDMMC::-2};
system() {	
	let upSeconds=$(cat /proc/uptime | cut -d ' ' -f1 | cut -d '.' -f1);
	let secs=$((${upSeconds}%60))
	let mins=$((${upSeconds}/60%60))
	let hours=$((${upSeconds}/3600%24))
	let days=$((${upSeconds}/86400))
	if [[ "${days}" -ne "0" ]]; then
		UPTIME="${days}d ";
	fi
	UPTIME="$UPTIME${hours}h ${mins}m ${secs}s"
	#let upSeconds=$(cat /proc/uptime | cut -d ' ' -f1 | cut -d '.' -f1);let secs=$((${upSeconds}%60));let mins=$((${upSeconds}/60%60));let hours=$((${upSeconds}/3600%24));let days=$((${upSeconds}/86400));UPTIME="${days}d ";UPTIME="$UPTIME${hours}h ${mins}m ${secs}s";echo $UPTIME
	USERS="$(who | cut -d ' ' -f1 | sort | uniq | wc -l) users"
	LOAD="$(cat /proc/loadavg)"
	MIN1="$(echo $LOAD | awk '{ print $1}')"
	MIN5="$(echo $LOAD | awk '{ print $2}')"
	MIN15="$(echo $LOAD | awk '{ print $3}')"
	TASKS="$(echo $LOAD | awk '{ print $4}')"
	readarray -t IPADDRESSES <<< $IPADDRESS
	_placeTitle "System Infomation"
	_placeLine "  - Uptime:" "$UPTIME"
	_placeLine "  - Users:" "$USERS"
	_placeLine "  - Load (1,5,15-min avg):" "$MIN1, $MIN5, $MIN15"
	_placeLine "  - Queued Tasks:" "$TASKS"
	#_placeLine "  - Watchdog:" "$WDOGPID"
	IPADDRESSES_len=${#IPADDRESSES[@]}
	for (( i = 0; i < $IPADDRESSES_len; i++ )); do
		theip="${IPADDRESSES[$i]}"
		if [[ "$i" -eq 0 ]]; then
			_placeLine "  - IP Addresses:" "$theip"
		else
			_placeLine "" "$theip"
		fi
	done
	
}

geo(){
	_placeTitle "Geographic Information"
	out=$(curl -m 1 -s ipinfo.io)
	if [[ "$out" != *"timed"* ]]; then
		PUBIP=$(echo "$out" | grep ip\" | awk '{print $2}' | sed -e 's/^"//' -e 's/",$//' -e 's/"$//')
		CITY=$(echo "$out" | grep city | awk '{print $2}' | sed -e 's/^"//' -e 's/",$//' -e 's/"$//')
		REGION=$(echo "$out" | grep region | awk '{print $2}' | sed -e 's/^"//' -e 's/",$//' -e 's/"$//')
		COUNTRY=$(echo "$out" | grep country | awk '{print $2}' | sed -e 's/^"//' -e 's/",$//' -e 's/"$//')
		ZIP=$(echo "$out" | grep postal | awk '{print $2}' | sed -e 's/^"//' -e 's/",$//' -e 's/"$//')
		LL=$(echo "$out" | grep loc | awk '{print $2}' | sed -e 's/^"//' -e 's/",$//' -e 's/"$//')
		ORG=$(echo "$out" | grep org | sed -e 's/"org"://'| sed -e 's/^   "//' -e 's/",$//' -e 's/"$//')
		_placeLine "  - Public IP:" "$PUBIP"
		_placeLine "  - City:" "$CITY"
		_placeLine "  - Region:" "$REGION"
		_placeLine "  - Country:" "$COUNTRY"
		_placeLine "  - Postal:" "$ZIP"
		_placeLine "  - Lat/Long:" "$LL"
		_placeLine "  - organization:" "$ORG"
	else
		_placeLine "  - timed out reaching ipinfo.io"
	fi
}

firmware(){
	currentV=$(grep -ne 'version' /wigwag/etc/versions.json 2> /dev/null | xargs | awk -F ' ' '{print $8}')
	userV=$(grep -ne 'version' /mnt/.overlay/user/slash/wigwag/etc/versions.json 2> /dev/null | xargs | awk -F ' ' '{print $8}')
	upgradeV=$(grep -ne 'version' /mnt/.overlay/upgrade/wigwag/etc/versions.json 2> /dev/null | xargs | awk -F ' ' '{print $8}')
	factoryV=$(grep -ne 'version' /mnt/.overlay/factory/wigwag/etc/versions.json 2> /dev/null | xargs | awk -F ' ' '{print $8}')
	#dd if=/dev/$USEDMMC of=/tmp/uboot.img seek=8 bs=1024 count=100 >> /dev/null 2>&1
	#ubootV=$(grep -a "WigWag-U-boot-version_id" /tmp/uboot.img | tail -1 | awk '{print $2}')
	if [[ -e /mnt/.boot/version ]]; then
		source /mnt/.boot/version
		bootV=$bootversion
	else
		bootV="unk"
	fi
	if [[ "$initramfsversion" = "" ]]; then
		initV="unk"
	else
		initV="$initramfsversion"
	fi
	kernelV=$(uname -r)
	rm -rf /tmp/uboot.img
	currentV=${currentV%%,*}
	userV=${userV%%,*}
	upgradeV=${upgradeV%%,*}
	factoryV=${factoryV%%,*}
	if [[ "$userV" = "" ]]; then
		userV="  ^  "
	fi
	if [[ "$upgradeV" = "" ]]; then
		upgradeV="  ^  "
	fi
	if [[ "$factoryV" = "" ]]; then
		factoryV="  ^  "
	fi
	Pschema="4Gb"
	echo "${NORM}"
	_placeTitle "Firmware Version Information"
	_placeLine "  - Pelion Edge Version:" "$currentV"
	if [[ $PTYPE = 1 ]]; then
		_placeLine "  - Overlay / Partition:" "$currentV"
		_placeLine "  - User Partition:" "$userV"
		_placeLine "  - Upgrade Partition:" "$upgradeV"
		_placeLine "  - Factory Partition:" "$factoryV"
		_placeLine "  - Partition Schema:" "$Pschema"
	fi
	_placeLine "  - Kernel Version:" "$kernelV"

}

account(){
	if [ -d /userdata/mbed ]; then
		SN=$serialNumber
		DID=$deviceID
		CLOUDURL=$cloudAddress
		EDGECORESTATUS=$(curl -s http://localhost:9101/status)
		AccountID=$(jsonParse $EDGECORESTATUS account-id)
		Status=$(jsonParse $EDGECORESTATUS status)
		_placeTitle "Account Infomation"
		_placeLine "  - Serial Number:" "$SN"
		_placeLine "  - Device ID:" "$DID"
		_placeLine "  - Cloud Server:" "$CLOUDURL"
		_placeLine "  - AccountID:" "$AccountID"
		_placeLine "  - Status:" "$Status"
	else
		SN=$relayID
		PAIRINGCODE=$pairingCode
		CLOUDURL=$cloudURL
		_placeTitle "Account Infomation"
		_placeLine "  - Serial Number:" "$SN"
		_placeLine "  - Pairing Code:" "$PAIRINGCODE"
		_placeLine "  - Cloud Server:" "$CLOUDURL"
	fi
}

hardware(){
	HWV=$hardwareVersion
	ETHERNETMAC=$(cat /sys/class/net/eth0/address)
	local CPUCOUNT=$(grep -c processor /proc/cpuinfo)
	local DIETEMP=$(cat /sys/devices/virtual/thermal/thermal_zone0/temp)
	if [[ "$DIETEMP" != "" ]]; then
		DIETEMP=$(_div1000 $DIETEMP)" C"
	fi
	_placeTitle "Hardware Infomation"
	_placeLine "  - Hardware Version:" "$HWV"
	_placeLine "  - Ethernet Mac:" "$ETHERNETMAC"
	_placeLine "  - Physical Memory:" "$MEM MB"
	_placeLine "  - SOC die tempurature:" "$DIETEMP"
	_placeLine "  - CPU Count:" "$CPUCOUNT"
	_placeLine "  - CPU Stats:" "Current\tMinimum\tMaximum  "
	for (( i = 0; i < $CPUCOUNT; i++ )); do
		curspeed=$(cat /sys/devices/system/cpu/cpu$i/cpufreq/scaling_cur_freq)
		maxspeed=$(cat /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq)
		minspeed=$(cat /sys/devices/system/cpu/cpu$i/cpufreq/scaling_min_freq)
		curspeed=$(_div1000 $curspeed)"Mhz"
		maxspeed=$(_div1000 $maxspeed)"Mhz"
		minspeed=$(_div1000 $minspeed)"Mhz"
		_placeLine "    - CPU$i:" "$curspeed\t$minspeed\t$maxspeed"
	done
}

manufacturing(){
	_placeTitle "Factory Manufacturing Infomation"
	_placeLine "  - Build Date:" "$YEAR-$MONTH-$BATCH"
}


# manufacturing
# #echo "123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
# for (( x = 1; x < 42; x++ )); do
# 	txt=""
# 	for (( i = 1; i < $x; i++ )); do
# 		txt="$txt".
# 	done
# 	_placeLine "$txt"
# 	echo "${CYAN}-${NORM}"
# done
# exit

_pad(){
	pad="$1"
	str="$2"
	size=${#str}
	out="";
	if [[ "$size" -eq 1 ]]; then
		for (( i = 0; i < $pad; i++ )); do
			out=" $out"
		done
	elif [[ "$size" -eq 2 ]]; then
		for (( i = 0; i < $(( $pad - 2 )); i++ )); do
			out=" $out"
		done
	fi
	echo "$out$str"
}

let PSSTOT=0;
_memperf(){
	name="$1"
	pgr="$2"
	pup="90min"
	pid=$(pgrep -f "$2")
	if [[ $pid != "" ]]; then
		et=$(ps -o etime= -p "$pid");
		if [[ "$et" = *"-"* ]]; then 
			pupd=$(echo $et | awk -F '-' '{print $1}')
		else
			pupd=0
		fi
		puph=$(echo $et | awk -F ':' '{print $1}');
		pupm=$(echo $et | awk -F ':' '{print $2}');
		pups=$(echo $et | awk -F ':' '{print $3}');
		upSeconds=$(ps -o etimes= -p "$pid");
		let secs=$((${upSeconds}%60))
		let mins=$((${upSeconds}/60%60))
		let hours=$((${upSeconds}/3600%24))
		let days=$((${upSeconds}/86400))
		UPTIME=""
		if [[ "${days}" -ne "0" ]]; then
			UPTIME="$(_pad 1 $days)d ";
		else
			UPTIME="$(_pad 1 0)d ";
		fi
		UPTIME="$UPTIME$(_pad 1 $hours)h $(_pad 1 $mins)m "
		Share=$(_div1024 $(echo 0 $(awk '/Shared/ {print "+", $2}' /proc/$pid/smaps) | bc) )
		Priv=$(_div1024 $(echo 0 $(awk '/Private/ {print "+", $2}' /proc/$pid/smaps) | bc) )
		Swap=$(_div1024 $(echo 0 $(awk '/Swap/ {print "+", $2}' /proc/$pid/smaps) | bc) )
		Virtual=$(_div1024 $(echo 0 $(awk '/Size/ {print "+", $2}' /proc/$pid/smaps) | bc) )
		Ref=$(_div1024 $(echo 0 $(awk '/Referenced/ {print "+", $2}' /proc/$pid/smaps) | bc) )
		Pss=$(_div1024 $(echo 0 $(awk '/Pss/ {print "+", $2}' /proc/$pid/smaps) | bc) )
		Rss=$(_div1024 $(echo 0 $(awk '/Rss/ {print "+", $2}' /proc/$pid/smaps) | bc) )
		PSSTOT=$(bc <<< "scale=1; $PSSTOT + $Pss")
		#_placeLine "  - $name ($pid):" "$Pss\t$Rss\t$Share\t$Priv\t$Size\t$Ref"
		_placeLine "  - $name ($pid):" "$UPTIME\t$Pss\t$Share\t$Rss\t$Virtual"
	fi
}

performance(){
	_placeTitle "Key Process Memory Infomation (MB)"
	_placeLine "  Stats in MB and time" "Uptime\t\tPss\tShared\tRss\tVirtual"
	_memperf "edge-core" "edge-core"
	_memperf "edge-proxy" "edge-proxy"
	_memperf "maestro" "maestro-config.yaml"
	_memperf "fluentbit" "td-agent-bit"
	_memperf "devicedb" "devicedb.yaml"
	_memperf "relay-term" "relay-term/src"
	_memperf "edge-kubelet" "kubelet --root-dir"
	_memperf "docker" "dockerd"
	_memperf "containerd" "containerd"
}

memory(){
	_placeTitle "System Memory"
	_placeLine "  - Used/Total:" "$USED/$MEM MB\t($UMP%)"
	UMP=$(_percentage $PSSTOT $MEM)
	_placeLine "  - Key Proccesses:" "$PSSTOT MB\t($UMP%) "
	UMP=$(_percentage $volatilePSS $MEM)
	_placeLine "  - Volatile loging:" "$volatilePSS MB\t\t($UMP%)"
	r2=$(bc <<< "scale=1; $MEM - $USED")
	r2=$(bc <<< "scale=1; $AVAILABLE - $r2 ")
	remainder=$(bc <<< "scale=1; $volatilePSS + $PSSTOT + $r2")
	remainder=$(bc <<< "scale=1; $USED - $remainder")
	UMP=$(_percentage $remainder $MEM )
	#_placeLine "  - Other:" "$remainder MB\t\t($UMP%)"
	UMP=$(_percentage $AVAILABLE $MEM)
	_placeLine "  - True Available Mem:" "$AVAILABLE MB\t\t($UMP%)"
}



Stats(){
	_placeHeader "Relay Information utility version $version"
}

_placeAbout(){
	echo -e "$1" "${CYAN}$2 ${NORM}"
}

about(){
	_placeHeader "About"
	_placeTitle "System Memory"
	_placeAbout "  Read about memory allocation:" "http://www.linuxatemyram.com/"
	_placeAbout "  - Physcial Memory:" "How much installed physical ram the system has"
	_placeAbout "  - Memory Useage:" "MemoryUsed/MemoryAvaiable (as a percentage)"
	_placeAbout "  - True Available Mem:" "How much mem can go to processes (minus cache)"
	_placeTitle "Process Memory"
	_placeAbout "  Read about process memory:" "https://goo.gl/wvUhBi"
	_placeAbout "  - Pss:" " Proportional Set Size, overall memory indicator (Rss adjusted for sharing)"
	_placeAbout "  - Rss:" " resident memory useage, all memory the process ueses (includes shared mem)"
	_placeAbout "  - Shared:" " memory that this process shares with other processes"
	_placeAbout "  - Privte:" " private memory used by this process, check for mem leaks here"
	_placeAbout "  - Virtual:" "total virtual space for the process"
	_placeAbout "  - Referenced: " " ammount of memory current marked as referenced or accessed"
}

showthesticker(){
	if [ -d /userdata/mbed]; then
		_placeTitle "Factory Label"
		d="{\"EID\":\"$enrollmentID\"}"
		qrcode-terminal -l "L" -f "black" -b "white" "$d"
	else
		_placeTitle "Factory Label"
		d="{\"ID\":\"$relayID\",\"PC\":\"$pairingCode\"}"
		qrcode-terminal -l "L" -f "black" -b "white" "$d"
	fi
}

main(){
	load_statistics
	idmachine
	if [[ $about -eq 1 ]]; then
		about
	else
		Stats
		system
		geo
		firmware
		hardware
		account
		#manufacturing
		if [[ $memory -eq 1 ]]; then
			performance
			memory
		fi
		if [[ $showsticker -eq 1 ]]; then
			showthesticker 
		fi
	fi
}


declare -A hp=(
	[description]="Displays vital system information statistics and process data"
	[useage]="-options"
	[a]="about"
	[h]="help"
	[m]="memory information added"
	[s]="show qr sticker at the end"
	[r]="regenerate gateway statics"
	[e1]="\t${BOLD}${UND}displays vital system information and process data${NORM}\n\t\t$0${NORM}\n"
	)

argprocessor(){
	switch_conditions=$(COMMON_MENU_SWITCH_GRAB)
	while getopts "$switch_conditions" flag; do
		case $flag in
			a)  about=1; ;;
			#
			h) COMMON_MENU_HELP; exit; ;;
			#
			m) memory=1; ;;
			#
			r) regenerateStats=1; ;;
			#
			s) showsticker=1; ;;
			#
			\?) echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed.";COMMON_MENU_HELP;exit; ;;
			#
		esac
	done
	shift $(( OPTIND - 1 ));
	main "$@"
}

argprocessor "$@"

